---
refresh_interval: 0 # seconds
max_price: 800 # dollars/euros/etc
urls:
  - https://www.amazon.com/gp/product/B08HBJB7YD#aod
  - https://www.amazon.com/gp/product/B08KWLMZV4#aod
  - https://www.amazon.com/gp/product/B08LF1CWT2#aod
  - https://www.amazon.com/gp/product/B08164VTWH#aod
  - https://www.amazon.com/gp/product/B08HH5WF97#aod
...
