---
refresh_interval: 1 # seconds
max_price: 2000 # dollars/euros/etc
urls:
  - https://www.amazon.com/gp/product/B0815JJQQ8#aod # AMD Ryzen Threadripper 3970X 1999
  - https://www.amazon.com/gp/product/B08KTYZXR9#aod # GIGABYTE AORUS GeForce RTX 3090 Master 1900
  - https://www.amazon.com/gp/product/B08J5F3G18#aod # EVGA GeForce RTX 3090 FTW3 Ultra Gaming, 24GB GDDR6X 1850
  - https://www.amazon.com/gp/product/B08HJGNJ81#aod # ASUS TUF Gaming NVIDIA GeForce RTX 3090 1850
  - https://www.amazon.com/gp/product/B08J6GMWCQ#aod # ASUS ROG STRIX NVIDIA GeForce RTX 3090 2000


...
