---
refresh_interval: 1 # seconds
max_price: 1600 # dollars/euros/etc
urls:
  - https://www.amazon.com/gp/product/B08Q36SRKK#aod # PowerColor AMD Radeon RX 6900 XT 1600
  - https://www.amazon.com/gp/product/B08R81J62G#aod # ASUS TUF Gaming AMD Radeon RX 6900 XT 1500
  - https://www.amazon.com/gp/product/B08S6Z2HGW#aod # ASUS ROG Strix LC AMD Radeon RX 6900 XT 1600
  - https://www.amazon.com/gp/product/B08QQFW9YS#aod # Sapphire 11308-01-20G Nitro+ AMD Radeon RX 6900 XT 1450
  - https://www.amazon.com/gp/product/B08Q9SCPGD#aod # XFX Speedster MERC319 AMD Radeon RX 6900 XT 1450
...
