---
refresh_interval: 0 # seconds
max_price: 1400 # dollars/euros/etc
urls:
  - https://www.amazon.com/gp/product/B0815JGCXP#aod # RYZEN 3960 1399
  - https://www.amazon.com/gp/product/B08Q9SCPGD#aod # XFX MERC139 1399
...
